name: CI
on:
  pull_request: {}
  push:
    branches: [main]

jobs:
  run:
    name: Build, Validate, and Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: w3c/spec-prod@v2
        with:
          GH_PAGES_BRANCH: gh-pages
          BUILD_FAIL_ON: nothing
          SOURCE: spec/index.bs
          DESTINATION: index.html
          TOOLCHAIN: bikeshed
          VALIDATE_MARKUP: false
